name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Dev
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/learn-CI-CD/myproject
            git pull origin dev
            docker-compose up -d --build
